-- Staging-only draft player seed
-- 15 QBs and 24 RBs for 4-team and 6-team draft testing.
-- Fictional players; safe to rerun.

INSERT INTO players (
    id,
    full_name,
    first_name,
    last_name,
    position,
    team,
    conference,
    year,
    height,
    weight,
    season,
    active,
    last_seen_at,
    raw
)
VALUES
(
    'staging-qb-001',
    'Mason Carter',
    'Mason',
    'Carter',
    'QB',
    'Wyoming',
    'Mountain West',
    'Junior',
    '6-2',
    215,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-002',
    'Ethan Brooks',
    'Ethan',
    'Brooks',
    'QB',
    'Colorado',
    'Big 12',
    'Senior',
    '6-3',
    220,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-003',
    'Caleb Turner',
    'Caleb',
    'Turner',
    'QB',
    'Nebraska',
    'Big Ten',
    'Sophomore',
    '6-1',
    205,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-004',
    'Jordan Hayes',
    'Jordan',
    'Hayes',
    'QB',
    'Kansas State',
    'Big 12',
    'Junior',
    '6-4',
    225,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-005',
    'Logan Pierce',
    'Logan',
    'Pierce',
    'QB',
    'Utah',
    'Big 12',
    'Senior',
    '6-2',
    218,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-006',
    'Noah Bennett',
    'Noah',
    'Bennett',
    'QB',
    'Iowa State',
    'Big 12',
    'Junior',
    '6-3',
    212,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-007',
    'Aiden Foster',
    'Aiden',
    'Foster',
    'QB',
    'Minnesota',
    'Big Ten',
    'Sophomore',
    '6-2',
    210,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-008',
    'Connor Reed',
    'Connor',
    'Reed',
    'QB',
    'Arizona',
    'Big 12',
    'Senior',
    '6-4',
    224,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-009',
    'Luke Simmons',
    'Luke',
    'Simmons',
    'QB',
    'Oklahoma State',
    'Big 12',
    'Junior',
    '6-1',
    208,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-010',
    'Dylan Price',
    'Dylan',
    'Price',
    'QB',
    'Wisconsin',
    'Big Ten',
    'Senior',
    '6-3',
    222,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-011',
    'Cameron Ellis',
    'Cameron',
    'Ellis',
    'QB',
    'Texas Tech',
    'Big 12',
    'Sophomore',
    '6-2',
    206,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-012',
    'Tyler Grant',
    'Tyler',
    'Grant',
    'QB',
    'Michigan State',
    'Big Ten',
    'Junior',
    '6-4',
    226,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-013',
    'Brady Morgan',
    'Brady',
    'Morgan',
    'QB',
    'Baylor',
    'Big 12',
    'Senior',
    '6-3',
    219,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-014',
    'Owen Parker',
    'Owen',
    'Parker',
    'QB',
    'Illinois',
    'Big Ten',
    'Sophomore',
    '6-1',
    204,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-qb-015',
    'Jack Coleman',
    'Jack',
    'Coleman',
    'QB',
    'TCU',
    'Big 12',
    'Junior',
    '6-2',
    214,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"QB"}'::jsonb
),
(
    'staging-rb-001',
    'Marcus Hill',
    'Marcus',
    'Hill',
    'RB',
    'Wyoming',
    'Mountain West',
    'Junior',
    '5-11',
    205,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-002',
    'Devin Ross',
    'Devin',
    'Ross',
    'RB',
    'Colorado',
    'Big 12',
    'Senior',
    '6-0',
    212,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-003',
    'Trey Lawson',
    'Trey',
    'Lawson',
    'RB',
    'Nebraska',
    'Big Ten',
    'Sophomore',
    '5-10',
    198,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-004',
    'Jayden Cole',
    'Jayden',
    'Cole',
    'RB',
    'Kansas State',
    'Big 12',
    'Junior',
    '5-11',
    210,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-005',
    'Malik Porter',
    'Malik',
    'Porter',
    'RB',
    'Utah',
    'Big 12',
    'Senior',
    '6-0',
    218,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-006',
    'Andre Lewis',
    'Andre',
    'Lewis',
    'RB',
    'Iowa State',
    'Big 12',
    'Junior',
    '5-9',
    195,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-007',
    'Darius King',
    'Darius',
    'King',
    'RB',
    'Minnesota',
    'Big Ten',
    'Sophomore',
    '5-11',
    207,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-008',
    'Xavier Bryant',
    'Xavier',
    'Bryant',
    'RB',
    'Arizona',
    'Big 12',
    'Senior',
    '6-1',
    220,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-009',
    'Elijah Moore',
    'Elijah',
    'Moore',
    'RB',
    'Oklahoma State',
    'Big 12',
    'Junior',
    '5-10',
    202,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-010',
    'Chris Daniels',
    'Chris',
    'Daniels',
    'RB',
    'Wisconsin',
    'Big Ten',
    'Senior',
    '6-0',
    215,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-011',
    'Jalen Scott',
    'Jalen',
    'Scott',
    'RB',
    'Texas Tech',
    'Big 12',
    'Sophomore',
    '5-9',
    192,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-012',
    'Isaiah Green',
    'Isaiah',
    'Green',
    'RB',
    'Michigan State',
    'Big Ten',
    'Junior',
    '5-11',
    209,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-013',
    'Kendrick Bell',
    'Kendrick',
    'Bell',
    'RB',
    'Baylor',
    'Big 12',
    'Senior',
    '6-0',
    216,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-014',
    'Nathan Ward',
    'Nathan',
    'Ward',
    'RB',
    'Illinois',
    'Big Ten',
    'Sophomore',
    '5-10',
    200,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-015',
    'Terrence Young',
    'Terrence',
    'Young',
    'RB',
    'TCU',
    'Big 12',
    'Junior',
    '5-11',
    211,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-016',
    'Rashad Walker',
    'Rashad',
    'Walker',
    'RB',
    'Cincinnati',
    'Big 12',
    'Senior',
    '6-0',
    219,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-017',
    'Miles Carter',
    'Miles',
    'Carter',
    'RB',
    'Northwestern',
    'Big Ten',
    'Sophomore',
    '5-9',
    194,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-018',
    'Keon Harris',
    'Keon',
    'Harris',
    'RB',
    'Houston',
    'Big 12',
    'Junior',
    '5-10',
    203,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-019',
    'Damien Brooks',
    'Damien',
    'Brooks',
    'RB',
    'Purdue',
    'Big Ten',
    'Senior',
    '6-1',
    221,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-020',
    'Zion Mitchell',
    'Zion',
    'Mitchell',
    'RB',
    'UCF',
    'Big 12',
    'Sophomore',
    '5-11',
    206,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-021',
    'Trevor James',
    'Trevor',
    'James',
    'RB',
    'Indiana',
    'Big Ten',
    'Junior',
    '5-10',
    201,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-022',
    'Bryce Cooper',
    'Bryce',
    'Cooper',
    'RB',
    'West Virginia',
    'Big 12',
    'Senior',
    '6-0',
    217,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-023',
    'Camden White',
    'Camden',
    'White',
    'RB',
    'Maryland',
    'Big Ten',
    'Sophomore',
    '5-9',
    193,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
),
(
    'staging-rb-024',
    'Jordan Fields',
    'Jordan',
    'Fields',
    'RB',
    'Arizona State',
    'Big 12',
    'Junior',
    '5-11',
    208,
    2026,
    TRUE,
    NOW(),
    '{"source":"staging-seed","draftable":true,"position":"RB"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    position = EXCLUDED.position,
    team = EXCLUDED.team,
    conference = EXCLUDED.conference,
    year = EXCLUDED.year,
    height = EXCLUDED.height,
    weight = EXCLUDED.weight,
    season = EXCLUDED.season,
    active = TRUE,
    last_seen_at = NOW(),
    raw = EXCLUDED.raw;
