-- College Fantasy Football Postgres schema
-- This schema is aligned with the backend search expectations (players joined to teams)
-- and is structured for CFBD-backed ingestion with category-aware player stats.

-- Enable trigram indexes for flexible name search.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Teams reference core CFBD identifiers.
CREATE TABLE IF NOT EXISTS teams (
    id              BIGINT PRIMARY KEY, -- CFBD team ID
    school          TEXT NOT NULL,
    mascot          TEXT,
    abbreviation    TEXT,
    conference      TEXT,
    division        TEXT,
    color           TEXT,
    alt_color       TEXT,
    logos           JSONB,
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_teams_conference ON teams (conference);

-- Players are keyed by CFBD player ID (text to support future providers) and keep raw JSON for forward compatibility.
CREATE TABLE IF NOT EXISTS players (
    id               TEXT PRIMARY KEY, -- CFBD player ID
    full_name        TEXT NOT NULL,
    first_name       TEXT,
    last_name        TEXT,
    position         TEXT,
    team             TEXT,
    conference       TEXT,
    year             TEXT,
    height           TEXT,
    weight           INTEGER,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw              JSONB
);

CREATE INDEX IF NOT EXISTS idx_players_name_trgm ON players USING gin (full_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_players_position ON players (position);
CREATE INDEX IF NOT EXISTS idx_players_conference ON players (conference);

-- Games are optional but useful for linking stats.
CREATE TABLE IF NOT EXISTS games (
    id               BIGINT PRIMARY KEY, -- CFBD game ID
    season           INT NOT NULL,
    week             INT,
    season_type      TEXT,
    start_date       TIMESTAMPTZ,
    home_team        TEXT,
    away_team        TEXT,
    home_points      INT,
    away_points      INT,
    venue            TEXT,
    neutral_site     BOOLEAN,
    conference_game  BOOLEAN,
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

-- Player stats are category-aware. Defense is reserved for future ingestion.
CREATE TABLE IF NOT EXISTS player_stats (
    player_id    TEXT REFERENCES players(id) ON DELETE CASCADE,
    season       INT NOT NULL,
    week         INT,
    team         TEXT,
    conference   TEXT,
    category     TEXT NOT NULL CHECK (category IN ('passing', 'rushing', 'receiving', 'defense')),
    stat_name    TEXT NOT NULL,
    stat_value   NUMERIC,
    game_id      BIGINT REFERENCES games(id) ON DELETE SET NULL,
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (player_id, season, week, category, stat_name, game_id)
);

CREATE INDEX IF NOT EXISTS idx_player_stats_cat_week ON player_stats (category, season, week);
CREATE INDEX IF NOT EXISTS idx_player_stats_player ON player_stats (player_id);

-- Ingestion run ledger to track call counts, row counts, and status.
CREATE TABLE IF NOT EXISTS ingestion_runs (
    id            BIGSERIAL PRIMARY KEY,
    resource      TEXT NOT NULL, -- e.g., 'teams', 'players', 'stats'
    season        INT,
    week          INT,
    started_at    TIMESTAMPTZ DEFAULT NOW(),
    finished_at   TIMESTAMPTZ,
    status        TEXT, -- 'success', 'failed', 'skipped'
    call_count    INT DEFAULT 0,
    row_count     INT DEFAULT 0,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_ingestion_runs_resource ON ingestion_runs (resource, season, week, started_at DESC);

-- Site accounts and bearer sessions. Passwords are bcrypt hashes generated by the C++ API.
CREATE TABLE IF NOT EXISTS users (
  email TEXT PRIMARY KEY,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS auth_tokens (
  token TEXT PRIMARY KEY,
  email TEXT NOT NULL REFERENCES users(email) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_email ON auth_tokens(email);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires_at ON auth_tokens(expires_at);

-- Fantasy league ownership and settings.
CREATE TABLE IF NOT EXISTS leagues (
  id TEXT PRIMARY KEY,
  account_email TEXT NOT NULL,
  name TEXT NOT NULL,
  team_count INTEGER NOT NULL DEFAULT 10 CHECK (team_count BETWEEN 4 AND 16),
  scoring TEXT NOT NULL DEFAULT 'ppr' CHECK (scoring IN ('ppr', 'half_ppr', 'standard')),
  scoring_settings JSONB NOT NULL DEFAULT '{
    "passingYardsPerPoint": 25,
    "passingTd": 4,
    "interception": -2,
    "rushingYardsPerPoint": 10,
    "rushingTd": 6,
    "receivingYardsPerPoint": 10,
    "receivingTd": 6,
    "reception": 1,
    "fumbleLost": -2,
    "twoPointConversion": 2
  }'::jsonb,
  draft_type TEXT NOT NULL DEFAULT 'snake' CHECK (draft_type IN ('snake', 'auction')),
  draft_date TIMESTAMPTZ,
  draft_lobby_open BOOLEAN NOT NULL DEFAULT FALSE,
  draft_lobby_started_at TIMESTAMPTZ,
  roster_rules JSONB NOT NULL DEFAULT '{
    "qb": 1,
    "rb": 2,
    "wr": 2,
    "te": 1,
    "flex": 2,
    "bench": 6
  }'::jsonb,
  waiver_rules JSONB NOT NULL DEFAULT '{
    "mode": "free_agency",
    "claimDeadline": "",
    "freeAgencyLocked": false
  }'::jsonb,
  trade_rules JSONB NOT NULL DEFAULT '{
    "commissionerApproval": false,
    "expirationHours": 48
  }'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  invited_emails TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leagues_account_email ON leagues(account_email);

ALTER TABLE leagues ADD COLUMN IF NOT EXISTS waiver_rules JSONB NOT NULL DEFAULT '{
  "mode": "free_agency",
  "claimDeadline": "",
  "freeAgencyLocked": false
}'::jsonb;

ALTER TABLE leagues ADD COLUMN IF NOT EXISTS trade_rules JSONB NOT NULL DEFAULT '{
  "commissionerApproval": false,
  "expirationHours": 48
}'::jsonb;

CREATE TABLE IF NOT EXISTS league_members (
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('commissioner', 'member')),
  status TEXT NOT NULL DEFAULT 'invited' CHECK (status IN ('invited', 'active', 'removed')),
  invited_by_email TEXT,
  joined_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (league_id, email)
);

CREATE INDEX IF NOT EXISTS idx_league_members_email ON league_members(email);
CREATE INDEX IF NOT EXISTS idx_league_members_league_status ON league_members(league_id, status);

CREATE OR REPLACE FUNCTION enforce_three_leagues_per_account()
RETURNS TRIGGER AS $$
BEGIN
  IF (
    SELECT COUNT(*)
    FROM leagues
    WHERE account_email = NEW.account_email
      AND id <> NEW.id
  ) >= 3 THEN
    RAISE EXCEPTION 'Each account can have up to three leagues';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_three_leagues_per_account ON leagues;
CREATE TRIGGER trg_three_leagues_per_account
BEFORE INSERT ON leagues
FOR EACH ROW
EXECUTE FUNCTION enforce_three_leagues_per_account();

CREATE TABLE IF NOT EXISTS rosters (
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT NOT NULL,
  player_id TEXT NOT NULL,
  player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  roster_slot TEXT NOT NULL DEFAULT 'bench',
  acquired_via TEXT NOT NULL DEFAULT 'draft',
  acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (league_id, manager_email, player_id)
);

ALTER TABLE rosters ADD COLUMN IF NOT EXISTS player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE rosters ADD COLUMN IF NOT EXISTS roster_slot TEXT NOT NULL DEFAULT 'bench';

CREATE TABLE IF NOT EXISTS draft_states (
  league_id TEXT PRIMARY KEY REFERENCES leagues(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'open', 'paused', 'complete')),
  current_pick INTEGER NOT NULL DEFAULT 1,
  draft_order TEXT[] NOT NULL DEFAULT '{}',
  pick_clock_seconds INTEGER NOT NULL DEFAULT 90,
  pick_deadline TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE draft_states ADD COLUMN IF NOT EXISTS pick_clock_seconds INTEGER NOT NULL DEFAULT 90;
ALTER TABLE draft_states ADD COLUMN IF NOT EXISTS pick_deadline TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS draft_queues (
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT NOT NULL,
  queue JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (league_id, manager_email)
);

CREATE TABLE IF NOT EXISTS draft_picks (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT NOT NULL,
  pick_number INTEGER NOT NULL,
  player_id TEXT NOT NULL,
  player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (league_id, pick_number),
  UNIQUE (league_id, player_id)
);

CREATE TABLE IF NOT EXISTS waiver_claims (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT NOT NULL,
  add_player_id TEXT NOT NULL,
  add_player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  drop_player_id TEXT,
  priority INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);

ALTER TABLE waiver_claims ADD COLUMN IF NOT EXISTS add_player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS waiver_priorities (
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (league_id, manager_email)
);

CREATE TABLE IF NOT EXISTS trade_offers (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  offered_by_email TEXT NOT NULL,
  offered_to_email TEXT NOT NULL,
  offered_player_ids TEXT[] NOT NULL DEFAULT '{}',
  requested_player_ids TEXT[] NOT NULL DEFAULT '{}',
  offer_player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  request_player_name TEXT NOT NULL DEFAULT '',
  target_manager TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT '',
  requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'pending',
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

ALTER TABLE trade_offers ADD COLUMN IF NOT EXISTS offer_player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE trade_offers ADD COLUMN IF NOT EXISTS request_player_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE trade_offers ADD COLUMN IF NOT EXISTS request_player_name TEXT NOT NULL DEFAULT '';
ALTER TABLE trade_offers ADD COLUMN IF NOT EXISTS target_manager TEXT NOT NULL DEFAULT '';
ALTER TABLE trade_offers ADD COLUMN IF NOT EXISTS requires_approval BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE trade_offers ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE trade_offers DROP CONSTRAINT IF EXISTS trade_offers_status_check;
ALTER TABLE trade_offers ADD CONSTRAINT trade_offers_status_check CHECK (status IN ('pending', 'accepted', 'approved', 'declined', 'vetoed', 'cancelled', 'expired'));

CREATE TABLE IF NOT EXISTS transactions (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT,
  transaction_type TEXT NOT NULL,
  summary TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS league_matchups (
  id TEXT PRIMARY KEY,
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  week INTEGER NOT NULL DEFAULT 1,
  home_manager_email TEXT NOT NULL,
  away_manager_email TEXT,
  home_score NUMERIC NOT NULL DEFAULT 0,
  away_score NUMERIC NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'final')),
  finalized_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE league_matchups ADD COLUMN IF NOT EXISTS finalized_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS fantasy_player_scores (
  league_id TEXT NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
  manager_email TEXT NOT NULL,
  player_id TEXT NOT NULL,
  season INTEGER NOT NULL,
  week INTEGER NOT NULL,
  fantasy_points NUMERIC NOT NULL DEFAULT 0,
  stats JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (league_id, manager_email, player_id, season, week)
);

CREATE INDEX IF NOT EXISTS idx_rosters_league ON rosters(league_id);
CREATE INDEX IF NOT EXISTS idx_draft_picks_league_pick ON draft_picks(league_id, pick_number);
CREATE INDEX IF NOT EXISTS idx_waivers_league_status ON waiver_claims(league_id, status);
CREATE INDEX IF NOT EXISTS idx_waiver_priorities_league ON waiver_priorities(league_id, priority);
CREATE INDEX IF NOT EXISTS idx_trades_league_status ON trade_offers(league_id, status);
CREATE INDEX IF NOT EXISTS idx_transactions_league_created ON transactions(league_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_matchups_league_week ON league_matchups(league_id, week);
CREATE INDEX IF NOT EXISTS idx_fantasy_scores_league_week ON fantasy_player_scores(league_id, season, week);
