#!/usr/bin/env sh
set -eu

if [ -z "${CFF_API_BASE:-}" ]; then
  echo "CFF_API_BASE is required, for example https://college-ff-api.onrender.com/api" >&2
  exit 1
fi

ALLOW_LOCAL_DEMO="${CFF_ALLOW_LOCAL_DEMO:-false}"

rm -rf frontend-dist
mkdir -p frontend-dist
cp -R frontend/. frontend-dist/

cat > frontend-dist/config.js <<EOF
// Generated by scripts/render-build-frontend.sh during Render static deploy.
window.CFF_API_BASE = '${CFF_API_BASE}';
window.CFF_ALLOW_LOCAL_DEMO = ${ALLOW_LOCAL_DEMO};
EOF

echo "Frontend build ready in frontend-dist"
