#!/usr/bin/env sh
set -eu

if [ -z "${CFF_API_BASE:-}" ]; then
  echo "CFF_API_BASE is required, for example https://college-ff-api.onrender.com/api" >&2
  exit 1
fi

# Existing Render services may retain an older environment value until their
# Blueprint is manually synchronized. Migrate the known broken custom API host
# during the build so deployed browsers receive the working backend endpoint.
if [ "${CFF_API_BASE}" = "https://api.college-fantasy-football.com/api" ]; then
  CFF_API_BASE="https://college-ff-api.onrender.com/api"
fi

ALLOW_LOCAL_DEMO="${CFF_ALLOW_LOCAL_DEMO:-false}"
BUILD_COMMIT="${RENDER_GIT_COMMIT:-local}"
BUILD_BRANCH="${RENDER_GIT_BRANCH:-local}"
CACHE_VERSION="$(printf '%s' "${BUILD_COMMIT}" | tr -cd 'A-Za-z0-9._-')"
if [ -z "${CACHE_VERSION}" ]; then
  CACHE_VERSION="local"
fi

rm -rf frontend-dist
mkdir -p frontend-dist
cp -R frontend/. frontend-dist/

cat > frontend-dist/config.js <<EOF_CONFIG
// Generated by scripts/render-build-frontend.sh during Render static deploy.
window.CFF_API_BASE = '${CFF_API_BASE}';
window.CFF_ALLOW_LOCAL_DEMO = ${ALLOW_LOCAL_DEMO};
window.CFF_BUILD_COMMIT = '${BUILD_COMMIT}';
EOF_CONFIG
cat frontend/config.js >> frontend-dist/config.js

# Load compatibility helpers before the league page controller. Use awk and a
# temporary file instead of an in-place multiline sed expression so the build
# works consistently across GNU, BusyBox, and BSD-style tooling.
LEAGUE_HTML="frontend-dist/league.html"
if [ -f "${LEAGUE_HTML}" ] && ! grep -q 'runtime-compat.js' "${LEAGUE_HTML}"; then
  LEAGUE_TMP="${LEAGUE_HTML}.tmp"
  awk '
    /<script src="league\.js"><\/script>/ {
      print "  <script src=\"runtime-compat.js\"></script>"
    }
    { print }
  ' "${LEAGUE_HTML}" > "${LEAGUE_TMP}"
  mv "${LEAGUE_TMP}" "${LEAGUE_HTML}"
fi

# Version directly referenced JavaScript assets so HTML, state helpers, and
# page controllers always come from the same frontend build. Avoid sed -i and
# find -exec portability differences by writing each transformed file safely.
find frontend-dist -type f -name '*.html' -print | while IFS= read -r html_file; do
  html_tmp="${html_file}.tmp"
  sed "s#src=\"\([^\"]*\\.js\)\"#src=\"\\1?v=${CACHE_VERSION}\"#g" "${html_file}" > "${html_tmp}"
  mv "${html_tmp}" "${html_file}"
done

cat > frontend-dist/build-info.json <<EOF_BUILD
{"commit":"${BUILD_COMMIT}","branch":"${BUILD_BRANCH}","apiBase":"${CFF_API_BASE}"}
EOF_BUILD

echo "Frontend build ready in frontend-dist for commit ${BUILD_COMMIT}"
